version: '2'
services:
  eureka-service-repository:
    image: 585864718859.dkr.ecr.us-west-2.amazonaws.com/chinikom-user-login-service
    cpu_shares: 100
    mem_limit: 1073741824
   ports:
      - "9005:9005"
      - "9006:9006"
